version: "2.1"
services:    
  api:
    extends:
      file: api/docker-compose.yml
      service: api
      
  api-db:
    extends:
      file: api/docker-compose.yml
      service: api-db
  
  orders:
    extends:
      file: orders/docker-compose.yml
      service: orders

  orders-db:
    extends:
      file: orders/docker-compose.yml
      service: orders-db
      
  users:
    extends:
      file: users/docker-compose.yml
      service: users

  users-db:
    extends:
      file: users/docker-compose.yml
      service: users-db

  webserver:
    environment:
      API_URL: http://172.28.128.4:9000
    extends:
      file: webserver/docker-compose.yml
      service: webserver
